class HeatingHelper:
    STATE_MODE_MANUAL = 0
    STATE_MODE_COOLING = 1
    STATE_MODE_AUTO = 2

    OPERATING_MODE_HEATING = 1
    OPERATING_MODE_SUMMER = 3

    STATE_CLIME_SEASON_OFF = 0
    STATE_CLIME_SEASON_HEATING = 1
    STATE_CLIME_SEASON_COOLING = 2
