class SunProtectionHelper:
    STATE_ROLLERSHUTTER_DOWN = 0
    STATE_ROLLERSHUTTER_MAYBE_UP = 1
    STATE_ROLLERSHUTTER_UP = 2

    STATE_TERRACE_OPEN = 0
    STATE_TERRACE_MAYBE_CLOSED = 1
    STATE_TERRACE_CLOSED = 2
